### ISSUE TITLE
[#001] iOS: Xcode 프로젝트 / 아이패드 뷰 세팅

### ISSUE THREAD

**Issue by BumgeunSong** [naneun/todo-list#2]
iOS 기본 세팅

**Comment by JasonLee0223** [comment]
- CollectionView - Eddy 진행
- TableView - Jason 진행
- [x]  .gitignore 추가
- [x]  SplitView 생성
    - [x]  TableView 생성
    - [x]  CollectionView 생성
- [x]  MVC 구조로 파일 나누기
